-- V9: Seed common LeetCode tags
INSERT IGNORE INTO tags (name, category) VALUES
-- Data Structures
('Array', 'data_structure'),
('String', 'data_structure'),
('Hash Table', 'data_structure'),
('Linked List', 'data_structure'),
('Tree', 'data_structure'),
('Binary Tree', 'data_structure'),
('Graph', 'data_structure'),
('Stack', 'data_structure'),
('Queue', 'data_structure'),
('Heap', 'data_structure'),
('Trie', 'data_structure'),
('Matrix', 'data_structure'),
('Segment Tree', 'data_structure'),
('Binary Indexed Tree', 'data_structure'),
-- Algorithms
('Dynamic Programming', 'algorithm'),
('Greedy', 'algorithm'),
('Binary Search', 'algorithm'),
('Depth-First Search', 'algorithm'),
('Breadth-First Search', 'algorithm'),
('Backtracking', 'algorithm'),
('Two Pointers', 'algorithm'),
('Sliding Window', 'algorithm'),
('Recursion', 'algorithm'),
('Divide and Conquer', 'algorithm'),
('Sorting', 'algorithm'),
('Bit Manipulation', 'algorithm'),
('Math', 'algorithm'),
('Memoization', 'algorithm'),
('Union Find', 'algorithm'),
('Topological Sort', 'algorithm'),
('Shortest Path', 'algorithm'),
('Simulation', 'algorithm'),
('Design', 'algorithm'),
('Monotonic Stack', 'algorithm'),
('Prefix Sum', 'algorithm');
